# Generated by Django 4.2.4 on 2023-09-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_mentorfield_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorfield',
            name='hourly_rate',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
