# Generated by Django 4.2.4 on 2023-09-28 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_availability_mentoravailabily_delete_availabilities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentoravailabily',
            old_name='Availability',
            new_name='availability',
        ),
    ]
